package com.zx.module_supervise.module.daily.bean

/**
 * Created by dell on 2019-07-25
 */
data class DailyDetailBean(var fCreditInfo: String?,
                           var fBuildingGuid: String?,
                           var insertDate: Long?,
                           var fPhoneModify: String?,
                           var fLongitude: Double?,
                           var fBizlicNum: String?,
                           var fEntityGuid: String?,
                           var fIndustryCode: String?,
                           var fIsNew: Int?,
                           var id: String?,
                           var checkPlace: String?,
                           var fEntityName: String?,
                           var enterpriseSignDate: String?,
                           var fFoundDate: Long?,
                           var fGovernOrgCode: String?,
                           var checkPerson: String?,
                           var checkSign: String?,
                           var fAddress: String?,
                           var fBizScope: String?,
                           var illegal: String?,
                           var fStation: String?,
                           var fOrgCode: String?,
                           var fContactInfo: String?,
                           var fEntityId: String?,
                           var fLatitude: Double?,
                           var name: String?,
                           var fZmqType: String?,
                           var fMatchedType: String?,
                           var status: Int?,
                           var checkSignDate: Long??,
                           var fLegalPerson: String?,
                           var fUniscid: String?,
                           var fStationCode: String?,
                           var remark: String?,
                           var fEnttype: String?,
                           var fCreditLevel: String?,
                           var fEntityType: String?,
                           var fImgUrl: String?,
                           var result: Int?,
                           var fContactPeople: String?,
                           var fEnttypename: String?,
                           var fXySign: String?,
                           var fIndustryType: String?,
                           var fIsOnline: String?,
                           var fGridCode: String?,
                           var fIndustry: String?,
                           var fGovernOrg: String?,
                           var fTags: String?,
                           var fIndustryTypeCode: String?,
                           var fContactAddress: String?,
                           var insertDepartmentCode: String?,
                           var fFloor: String?,
                           var enterpriseName: String?,
                           var fRegOrg: String?,
                           var fLicenses: String?,
                           var fContactPhone: String?,
                           var fBizTypes: String?,
                           var checkDate: Long?,
                           var enterpriseSign: String?,
                           var insertPerson: String?,
                           var insertPersonId: String?,
                           var fGrid: String?,
                           var fAddrMatch: Int?,
                           var enterpriseId: String?,
                           var fPqType: String?,
                           var attachment: List<Attachment>?) {
    data class Attachment(var id: String?,
                          var realName: String?,
                          var saveName: String?,
                          var savePath: String?,
                          var saveDate: Long?,
                          var creditCode: String?,
                          var userId: String?,
                          var tableName: String?,
                          var itemId: String?,
                          var field: String?)
}