package com.zx.module_complain.module.info.bean

import java.io.Serializable

/**
 * Updated by dell on 2019-06-27
 */
data class DetailBean(var baseInfo: BaseInfo,
                      var statusInfo: List<StatusInfo>?,
                      var files: List<FileBean>?) : Serializable {
    data class BaseInfo(var fGuid: String?,
                        var fRegId: String?,
                        var fRegTime: Long?,
                        var fRegName: String?,
                        var fRegOrg: String?,
                        var fRegOrgCode: String?,
                        var fStatus: Int?,
                        var fNowDepartment: String?,
                        var fNextDeadline: String?,
                        var fShunt: String?,
                        var fShuntTime: String?,
                        var fDisposeUser: String?,
                        var fDisposeTime: String?,
                        var fCloseTime: Long?,
                        var fReceiveType: String?,
                        var fType: String?,
                        var fSource: String?,
                        var fName: String?,
                        var fGender: String?,
                        var fJob: String?,
                        var fRegPhone: String?,
                        var fNation: String?,
                        var fLocalConsumer: String?,
                        var fNationality: String?,
                        var fTelephone: String?,
                        var fCellphone: String?,
                        var fFax: String?,
                        var fEmail: String?,
                        var fContactInfo: String?,
                        var fAge: String?,
                        var fDisabled: String?,
                        var fProviderType: String?,
                        var fLicType: String?,
                        var fLicNum: String?,
                        var fWorkOrg: String?,
                        var fAddress: String?,
                        var fZipcode: String?,
                        var fEntityGuid: String?,
                        var fEntityName: String?,
                        var fEntityPhone: String?,
                        var fEntityIndustry: String?,
                        var fEntityAddress: String?,
                        var fProductName: String?,
                        var fBrandName: String?,
                        var fProductType: String?,
                        var fKeyword: String?,
                        var fConsumeType: String?,
                        var fNature: String?,
                        var fUrgency: String?,
                        var fSignificant: String?,
                        var fSpotNeed: String?,
                        var fMoney: String?,
                        var fCaseValue: String?,
                        var fEconomyLost: String?,
                        var fEventAddress: String?,
                        var fEventTime: Long??,
                        var fAffectedPeople: String?,
                        var fFollow: String?,
                        var fRepeatedly: String?,
                        var fGroup: String?,
                        var fResponse: String?,
                        var fSecrecy: String?,
                        var fOpenWeb: String?,
                        var fLongitude: Double,
                        var fLatitude: Double,
                        var fPushed: String?,
                        var fInputUser: String?,
                        var fInputTime: String?,
                        var fCount: String?,
                        var fLimitTime: Long?,
                        var fConsumeType1: String?,
                        var fContactBool: String?,
                        var fContactAvenue: String?,
                        var fAutocomId: String?,
                        var fFilename: String?,
                        var fFilepath: String?,
                        var fSegment: String?,
                        var fRecoupedeconomyLost: String?,
                        var fEntityType: String?,
                        var fCompStringType: String?,
                        var fMarketName: String?,
                        var fGoodsMark: String?,
                        var fProducerGrid: String?,
                        var fProducer: String?,
                        var fParts: String?,
                        var fSaleGrid: String?,
                        var fSale: String?,
                        var fMediationEnddate: String?,
                        var fInfringementType: String?,
                        var fObligationsFails: String?,
                        var fAdjustWay: String?,
                        var fFraudLogo: String?,
                        var fDisputeAmount: String?,
                        var fSpiritAmount: String?,
                        var fDoubleCompensation: String?,
                        var fMediationId: String?,
                        var fAcceptType: String?,
                        var fEmergencyState: String?,
                        var fHandleDepartment: String?,
                        var fUnitType: String?,
                        var fAgent: String?,
                        var fFeedbackRegistrar: String?,
                        var fCaseClues: String?,
                        var fConsumeType2: String?,
                        var fConsumeType3: String?,
                        var fConsumeType4: String?,
                        var fNature1: String?,
                        var fNature2: String?,
                        var fAgentPhone: String?,
                        var fBizNum: String?,
                        var fDelayFlag: String?,
                        var fRefundAmount: String?,
                        var fConfiscateAmount: String?,
                        var fFineAmount: String?,
                        var fRefundPeoplenum: String?,
                        var fCaseRegister: String?,
                        var fCaseType: String?,
                        var fCenepunish: String?,
                        var fCaseId: String?,
                        var fPrograme: String?,
                        var fCaseFillingDate: String?,
                        var fCaseCloseDate: String?,
                        var fCaseGrid: String?,
                        var fCaseAmount: String?,
                        var fCaseCharacter: String?,
                        var fLostMoney: String?,
                        var fGainMoney: String?,
                        var fFineMoney: String?,
                        var fPunishType: String?,
                        var fFake: String?,
                        var fForceMeasure: String?,
                        var fAzh: String?,
                        var fAcrossType: String?,
                        var fAcrossAmount: String?,
                        var fCasePlace: String?,
                        var fHurtType: String?,
                        var fHurtNumber: String?,
                        var fChangeNumber: String?,
                        var fLawerNumber: String?,
                        var fVehicleNumber: String?,
                        var fMarketNumber: String?,
                        var fSaleNumber: String?,
                        var fViolence: String?,
                        var fInjured: String?,
                        var fDead: String?,
                        var fCustomType: String?,
                        var fReduce: String?,
                        var fNone: String?,
                        var fCosumeConfirm: String?,
                        var fExcuteType: String?,
                        var fExcuteDate: String?,
                        var fStopDate: String?,
                        var fOpenId: String?,
                        var fAccept: String?,
                        var fProof: String?,
                        var fBriefInfo: String?,
                        var fContent: String?,
                        var fAdvice: String?,
                        var fMediationResult: String?,
                        var fFeedbackContent: String?,
                        var fIllegalType: String?,
                        var fGist: String?,
                        var fPunishResult: String?,
                        var fPunishGist: String?,
                        var fStopReason: String?,
                        var fCancelCondition: String?) : Serializable

    data class StatusInfo(var fGuid: String? = "",
                          var fBeforeStatus: Int? = 0,
                          var fStatus: Int? = 0,
                          var fDispose: String? = "",
                          var fDisposeDate: Long? = 0L,
                          var fUserId: String? = "",
                          var fRealName: String? = "",
                          var fDepartment: String? = "",
                          var fAccept: String? = "",
                          var fDisposeRemark: String? = "") : Serializable

    data class FileBean(var id: String?,
                        var realName: String?,
                        var saveName: String?,
                        var savePath: String?,
                        var saveDate: Long?,
                        var creditCode: String?,
                        var userId: String?,
                        var tableName: String?,
                        var itemId: String?,
                        var field: String?) : Serializable
}